### ISSUE TITLE
Boot Loop on Epic Rom

### ISSUE THREAD

**Issue by BigRocha** [kdrag0n/velocity_tissot#2]
hi, i am using Epic Rom (MIUI 10) and when i try to install velocity kernel the device enters on boot loop.. i really liked this kernel, can you make a fix for epic rom?

Rom link: https://sourceforge.net/projects/epic-rom/files/MiA1/8.9.20/

**Comment by kdrag0n** [comment]
No, I'm not interested in supporting MIUI. Get an 8.1 based MIUI first, this kernel won't work on Nougat.

**Comment by BigRocha** [comment]
Right.. so i cant use this kernel because i am using android 7.1.2..  i just need to add the usb wifi dongles usb support for the epic rom stock kernel.. can you help me with this? Do you have a guide for add drivers on kernel or something like that?
